export const config = {
  secret: process.env.APP_SECRET,
  algorithm: process.env.ENCRYPTION_ALGORITH,
  hashAlgorithm: process.env.HASH_ALGORITHM,
  domainURL: process.env.DOMAIN_URL,
  systemUserId: process.env.SYSTEM_USER_ID,
  systemRoleId: process.env.SYSTEM_ROLE_ID,
  systemDeptId: process.env.SYSTEM_DEPT_ID,
  chatRoleId: process.env.CHAT_ROLE_ID,
  sessionTimeOut: process.env.SESSION_TIMEOUT,
  chatAbandonedTimeout: process.env.CHAT_ABANDONED_TIMEOUT || 3,
  iv: process.env.IV,
  tenantId: process.env.DB_TENANT_ID,
  dbProperties: {
    database: process.env.DB_DATABASE,
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD,
    host: process.env.DB_HOST,
    dialect: process.env.DB_DIALECT,
    port: process.env.DB_PORT,
    schema: process.env.DB_SCHEMA,
    dialectOptions: {
      statement_timeout: 5000
    }
  },
  bcae: {
    host: process.env.SERVICE_HOST,
    port: process.env.CHATBOT_SERVICE_PORT
  },
  kafka: {
    clientId: process.env.KAFKA_CLIENT_ID,
    brokers: process.env.KAFKA_BROKERS.split(','),
    userGroup: 'user_group',
    userTopic: 'user_topic'
  },
  tibco: {
    apiEndPoint: 'http://172.17.21.6:9208',
    customerAPIEndPoint: 'http://172.17.21.6:9209',
    accessNumberAPI: '/aios/accessnumbers',
    iccidValidationAPI: '/aios/validateiccid',
    customerSummaryAPI: '/aios/customersummary',
    soapAPIEndpoint: 'http://172.17.21.6:9030',
    addBalanceAPI: '/addBalanceServiceBinding/addBalanceService',
    addBalanceMobileAPIEndpoint: 'http://172.17.21.6:9214',
    addBalanceMobileAPIEndpointImagine: 'http://172.17.21.6:9224',
    addBalanceMobileAPI: '/addbalance',
    ticketApiEndPoint: 'http://172.17.21.6:9211',
    ticketDetailsAPI: '/viewticket',
    ocsBarEndPoint: 'http://172.17.21.6:9212',
    ocsBarAPI: '/barsubscription',
    ocsUnBarEndPoint: 'http://172.17.21.6:9213',
    ocsUnBarAPI: '/unbarsubscription',
    fixedLineAddBalanceEndPoint: 'http://172.17.21.6:9146',
    fixedLineAddBalanceAPI: '/addbalance',
    ocsCustomerSummaryEndPoint: 'http://172.17.21.6:9043',
    ocsCustomerSummaryAPI: '/searchcustomer',
    username: 'Aios',
    passwd: '$Tibc0@Aios$',
    source: 'AIOS', customerStatusAPIEndPoint: 'http://172.17.21.6:9220',
    accountDetailsAPIEndPoint: 'http://172.17.21.6:9221',
    billInfoAPIEndPoint: 'http://172.17.21.6:9223',
    serviceStatusAPIEndPoint: 'http://172.17.21.6:9043',
    prepaidBoosterDetailsAPIEndPoint: 'http://172.17.21.6:9226',
    fixedlineServiceStatusAPIEndPoint: 'http://172.17.21.6:9228',
    fixedlinePlanInfoAPIEndPoint: 'http://172.17.21.6:9227',
    fixedlineBoosterDetailsAPIEndPoint: 'http://172.17.21.6:9145',
    prepaidCreditDetailsAPIEndPoint: 'http://172.17.21.6:9227',
    contractDetailsAPIEndPoint: 'http://172.17.21.6:9229',
    customerStatusAPI: '/checkcustomerexists',
    accountDetailsAPI: '/aios/getaccountdetails',
    billInfoAPI: '/aios/getBillInfo',
    serviceStatusAPI: '/searchcustomer',
    prepaidBoosterDetailsAPI: '/prepaid/querybalance',
    fixedlineServiceStatusAPI: '/aios/servicestatusfixedline',
    fixedlinePlanInfoAPI: '/planinfofixedline',
    fixedlineBoosterDetailsAPI: '/querybalance',
    prepaidCreditDetailsAPI: '/prepaidcredit',
    contractDetailsAPI: '/getcontractstatus'
  },
}
